### ISSUE TITLE
Can you publish data sets and models in Baidu cloud？Google hard disk downloads are all wrong, 

### ISSUE THREAD

**Issue by QQ2737499951** [ZhaoJ9014/High-Performance-Face-Recognition#7]
Can you publish data sets and models in Baidu cloud? Google hard disk downloads are all wrong, prompting too many people to download recently, has been blocked. Thank you

Download
Please refer to "./src/" and this link to access our full source codes and models (continue to update).
 **https://drive.google.com/drive/folders/15L-macCtlFDondqbDDoZFcz1Qe9bLqH4?usp=sharing**

![image](https://user-images.githubusercontent.com/33048209/59277990-bff38700-8c93-11e9-94f8-506f9f33c6b4.png)

![image](https://user-images.githubusercontent.com/33048209/59281070-3d6dc600-8c99-11e9-9d1e-9aeb1bf2eb79.png)

![image](https://user-images.githubusercontent.com/33048209/59281151-5b3b2b00-8c99-11e9-8e2b-c50f85611011.png)

**Comment by ZhaoJ9014** [comment]
Hi, for large datasets or models, we opt for google drive since baidu drive has limitation on the size of file per uploading. But for others, we have already provided both baidu drive and google drive links:)
